### ISSUE TITLE
Allow for disabling SSL validation

### ISSUE THREAD

**Issue by cygnetix** [StackStorm-Exchange/stackstorm-splunk#7]
For testing purposes it'd be great to have the option of disabling SSL verification. This seems like it'd be a simple change to add a "verify" option to splunk.yaml as the connection function supports this: http://docs.splunk.com/DocumentationStatic/PythonSDK/1.6.5/client.html

Currently I'm getting the following error on my development VM:
```ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)```

**Comment by LindsayHill** [comment]
Should be pretty straightforward to add - can you start a PR?

**Comment by cygnetix** [comment]
Will do. Working on some code now.
Thanks.

**Comment by LindsayHill** [comment]
👍 

Will review & merge when ready

**Comment by LindsayHill** [comment]
Resolved by #8
